#!/usr/bin/env node
/**
 * Fetches a fresh Dataverse access token (using the same MSAL cache as
 * the seed / schema scripts) and writes it to `.env.local` so the Vite
 * dev server can talk to Dataverse via the direct-API fallback path.
 *
 * Usage:  node scripts/dev-token.mjs
 *   then: npm run dev
 */
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { resolveToken } from './dataverse/auth.mjs'

const DV_URL = process.env.DATAVERSE_URL || 'https://org91869c7b.crm4.dynamics.com'

const token = await resolveToken(DV_URL)
if (!token) {
  console.error('❌  Could not obtain a Dataverse token.')
  process.exit(1)
}

const envPath = resolve(import.meta.dirname, '..', '.env.local')
const content = `# Auto-generated by scripts/dev-token.mjs — DO NOT commit
VITE_DATAVERSE_URL=${DV_URL}
VITE_DATAVERSE_TOKEN=${token}
`

writeFileSync(envPath, content, 'utf8')
console.log(`✅  .env.local written (token length: ${token.length})`)
console.log('   Run  npm run dev  to start with live Dataverse data.')
